---
  - name: My ELK Stack
    hosts: elkservers
    become: True
    tasks:
 
    - name: change the memory on the elk vm
      shell: sysctl -w vm.max_map_count=262144

    - name: install docker.io
      apt:
        force_apt_get: yes
        name: docker.io
        state: present

    - name: install python-pip
      apt:
        force_apt_get: yes
        name: python-pip
        state: present

    - name: install docker python module
      pip:
        name: docker
        state: present

    - name: download and launch a docker elk stack
      docker_container:
        name: elkstack
        image: sebp/elk
        state: started
        published_ports: 5601:5601
        published_ports: 9200:9200
        published_ports: 5044:5044

